apiVersion: batch/v1
kind: Job
metadata:
  name: create-admin-user
spec:
  template:
    metadata:
      name: create-admin-user
    spec:
      restartPolicy: Never
      containers:
      - name: create-admin-user
        image: gcr.io/okapi-173322/folio-toolkit
        env:
        - name: DB_HOST
          value: "<%= storage.host %>"
        - name: DB_PORT
          value: "<%= storage.port %>"
        - name: DB_DATABASE
          value: <%= storage.database %>
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: <%= storage.credentials_secret %>
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: <%= storage.credentials_secret %>
              key: password
        command: ["/usr/local/bin/folio/create_admin_user.sh"]
      - name: cloudsql-proxy
        command: ["/cloud_sql_proxy", "--dir=/cloudsql",
                    "-instances=<%= storage.instance %>=tcp:<%= storage.port %>",
                    "-credential_file=/secrets/cloudsql/credentials.json"]
        image: gcr.io/cloudsql-docker/gce-proxy:1.09
        imagePullPolicy: IfNotPresent
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
          - name: <%= storage.instance_credentials_secret %>
            mountPath: /secrets/cloudsql
            readOnly: true
          - name: ssl-certs
            mountPath: /etc/ssl/certs
          - name: cloudsql
            mountPath: /cloudsql
        resources: {}
      volumes:
      - name: <%= storage.instance_credentials_secret %>
        secret:
          secretName: <%= storage.instance_credentials_secret %>
      - name: ssl-certs
        hostPath:
          path: /etc/ssl/certs
      - name: cloudsql
        emptyDir:
