apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: mod-configuration
  name: mod-configuration
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8081
  selector:
    run: mod-configuration
  type: NodePort
status:
  loadBalancer: {}
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: mod-configuration
  name: mod-configuration
spec:
  replicas: 1
  selector:
    matchLabels:
      run: mod-configuration
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: mod-configuration
    spec:
      containers:
      - image: gcr.io/okapi-173322/folio-toolkit:1245am
        name: mod-configuration
        env:
        - name: REPO_NAME
          value: 'folio-org/mod-configuration'
        - name: REPO_VERSION
          value: 'master'
        - name: OKAPI_MODULE_SERVICE_NAME
          value: 'mod-configuration'
        - name: OKAPI_MODULE_DESCRIPTOR_PATH
          value: 'target/ModuleDescriptor.json'
        - name: DB_HOST
          value: "postgres"
        - name: DB_PORT
          value: "5432"
        - name: DB_DATABASE
          value: "folio"
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              key: username
              name: cloudsql-db-credentials-v2
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: cloudsql-db-credentials-v2
        command: ["/usr/local/bin/folio/install_java.sh"]
        args: ["java", "-jar", "mod-configuration-server/target/mod-configuration-server-fat.jar"]
        resources: {}
status: {}
