dist: trusty
sudo: required

#Use ruby environment
language: ruby
rvm:
  - 2.4.1

# Cache Gcloud SDK between commands
cache:
  directories:
    - "$HOME/google-cloud-sdk/"

# Install services
services:
  - docker

install: true
script: true

notifications:
  webhooks: https://fs-bitbot.herokuapp.com/travis
