dist: trusty
sudo: required

#Use ruby environment
language: ruby
rvm:
  - 2.4.1

# Cache Gcloud SDK between commands
cache:
  directories:
    - "$HOME/google-cloud-sdk/"

# Install services
services:
  - docker

# Set env vars
env:
  global:
    - GOOGLE_APPLICATION_CREDENTIALS=~/gcloud-service-key.json
    - PROJECT_ID=okapi-173322
    - CLUSTER_NAME=okapi-demo
    - CLOUDSDK_COMPUTE_ZONE=us-east1-b
    - DOCKER_IMAGE_NAME=gcr.io/okapi-173322/okapi-cluster

install: true
script: true

before_deploy:
  - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash > /dev/null; fi
  - source /home/travis/google-cloud-sdk/path.bash.inc
  - gcloud --quiet version
  - gcloud --quiet components update
  - gcloud --quiet components update kubectl

deploy:
  - provider: script
    script: ./deploy.sh
    skip_cleanup: true
    on:
      all_branches: true

notifications:
  webhooks: https://fs-bitbot.herokuapp.com/travis
