apiVersion: v1
kind: Service
metadata:
  name: <%= folio_module.name %>
  labels:
    run: <%= folio_module.name %>
spec:
  ports:
  - port: 8081
  selector:
    run: <%= folio_module.name %>
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: <%= folio_module.name %>
  namespace: default
  labels:
    run: <%= folio_module.name %>
spec:
  replicas: 1
  selector:
    matchLabels:
      run: <%= folio_module.name %>
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: <%= folio_module.name %>
    spec:
      containers:
        - name: <%= folio_module.name %>
          image: <%= folio_module.image %>:<%= folio_module.tag %>
          env:
            - name: DB_HOST
              value: "<%= storage.host %>"
            - name: DB_PORT
              value: "<%= storage.port %>"
            - name: DB_DATABASE
              value: <%= storage.database %>
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: <%= storage.credentials_secret %>
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: <%= storage.credentials_secret %>
                  key: password
        - image: gcr.io/cloudsql-docker/gce-proxy:1.09
          name: cloudsql-proxy
          command: ["/cloud_sql_proxy", "--dir=/cloudsql",
                      "-instances=<%= storage.instance %>=tcp:<%= storage.port %>",
                      "-credential_file=/secrets/cloudsql/credentials.json"]
          volumeMounts:
              - name: <%= storage.instance_credentials_secret %>
                mountPath: /secrets/cloudsql
                readOnly: true
              - name: ssl-certs
                mountPath: /etc/ssl/certs
              - name: cloudsql
                mountPath: /cloudsql
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      volumes:
      - name: <%= storage.instance_credentials_secret %>
        secret:
          secretName: <%= storage.instance_credentials_secret %>
      - name: ssl-certs
        hostPath:
          path: /etc/ssl/certs
      - name: cloudsql
        emptyDir:
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
