apiVersion: v1
kind: Service
metadata:
  labels:
    run: okapi
  name: okapi
  namespace: default
spec:
  type: NodePort
  ports:
    - port: 80
      protocol: TCP
      targetPort: 9130
  selector:
    run: okapi
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: okapi
  name: okapi
spec:
  replicas: 1
  selector:
    matchLabels:
      run: okapi
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: okapi
    spec:
      containers:
      - env:
        - name: DB_HOST
          value: "<%= storage.host %>"
        - name: DB_PORT
          value: "<%= storage.port %>"
        - name: DB_DATABASE
          value: "<%= storage.database %>"
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              key: username
              name: <%= storage.credentials_secret %>
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: <%= storage.credentials_secret %>
        - name: OKAPI_URL
          value: "http://localhost:9130"
        image: <%= okapi.image %>:<%= okapi.tag %>
        imagePullPolicy: Always
        name: okapi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      - command:
        - /cloud_sql_proxy
        - --dir=/cloudsql
        - -instances=<%= storage.instance %>=tcp:<%= storage.port %>
        - -credential_file=/secrets/cloudsql/credentials.json
        image: gcr.io/cloudsql-docker/gce-proxy:1.09
        imagePullPolicy: IfNotPresent
        name: cloudsql-proxy
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /secrets/cloudsql
          name: <%= storage.instance_credentials_secret %>
          readOnly: true
        - mountPath: /etc/ssl/certs
          name: ssl-certs
        - mountPath: /cloudsql
          name: cloudsql
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: <%= storage.instance_credentials_secret %>
        secret:
          defaultMode: 420
          secretName: <%= storage.instance_credentials_secret %>
      - hostPath:
          path: /etc/ssl/certs
        name: ssl-certs
      - emptyDir: {}
        name: cloudsql
